export_training_paths:  false
export_final_paths: false
epsilon:  1
min_epsilon: 0.01
max_epsilon: 1
epsilon_decay: 0.99999
discount_factor:  0.9
learning_rate:  0.2
episodes: 500000
test_episodes: 50000
wall_reward:  -1000
path_reward:  -1
target_reward:  1000
pickup_reward:  200
#stop_exploring_after: 150000 #optional
move_limit: 200 #optional
