export_training_paths:  False
export_test_paths: False
epsilon:  1
min_epsilon: 0.1
epsilon_decay: 0.999995
discount_factor:  0.9
learning_rate:  1
min_learning_rate: 0.1
learning_rate_decay: 0.999995
episodes: 1000000
test_episodes: 70000
wall_reward:  -300
path_reward:  -1
target_reward:  200
stop_exploring_after: 500000 #optional
move_limit: 40 #optional
iteration_export_cycle: 1000
test_export_cycle: 100
iteration_plot_cycle: 2000
