export_training_paths:  True
export_test_paths: True
epsilon:  1
epsilon_decay: 0.99999
discount_factor:  0.9
learning_rate:  0.2
episodes: 500000
test_episodes: 5000
wall_reward:  -1000
path_reward:  -1
target_reward:  1000
pickup_reward:  200
#stop_exploring_after: 150000 #optional
move_limit: 200 #optional
iteration_export_cycle: 1000
