export_training_paths:  false
export_final_paths: false
epsilon:  1
epsilon_decay: 0.999
discount_factor:  0.95
learning_rate:  0.95
episodes: 15000
wall_reward:  -200
path_reward:  -1
target_reward:  100
pickup_reward:  30
target_without_pickup_reward: -30
#stop_exploring_after: 15000 #optional
move_limit: 100 #optional
test_path_starting_points:
  - x:  6
    y:  0
  - x:  0
    y:  0
target:
    x: 0
    y: 0

